# Generated by Django 3.2 on 2021-04-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0003_auto_20210427_2028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Contact',
        ),
    ]
