# Generated by Django 3.2 on 2021-04-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0004_rename_reservation_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='products/', verbose_name='Image')),
            ],
        ),
    ]
