# Generated by Django 3.2 on 2021-04-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0005_trends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='products/', verbose_name='Image')),
            ],
        ),
    ]
