# Generated by Django 3.2 on 2021-04-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0006_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('icon', models.ImageField(default='default.jpg', upload_to='products/', verbose_name='Image')),
            ],
        ),
    ]
